Launcher3: Fix duplicated Bezier float coordinate in ic_recent_camera_locked
Remove duplicate float pair in SVG cubic Bezier curve command that caused
IllegalArgumentException: C needs to be followed by a multiple of 6 floats.